
package org.recefi.lab.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://server.lab.recefi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connect", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.Connect")
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.ConnectResponse")
    @Action(input = "http://server.lab.recefi.org/Server/connectRequest", output = "http://server.lab.recefi.org/Server/connectResponse")
    public int connect();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkWin", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.CheckWin")
    @ResponseWrapper(localName = "checkWinResponse", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.CheckWinResponse")
    @Action(input = "http://server.lab.recefi.org/Server/checkWinRequest", output = "http://server.lab.recefi.org/Server/checkWinResponse")
    public int checkWin();

    /**
     * 
     * @return
     *     returns java.util.List<org.recefi.lab.webservice.Cell>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBoard", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.GetBoard")
    @ResponseWrapper(localName = "getBoardResponse", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.GetBoardResponse")
    @Action(input = "http://server.lab.recefi.org/Server/getBoardRequest", output = "http://server.lab.recefi.org/Server/getBoardResponse")
    public List<Cell> getBoard();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkStart", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.CheckStart")
    @ResponseWrapper(localName = "checkStartResponse", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.CheckStartResponse")
    @Action(input = "http://server.lab.recefi.org/Server/checkStartRequest", output = "http://server.lab.recefi.org/Server/checkStartResponse")
    public boolean checkStart();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkMove", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.CheckMove")
    @ResponseWrapper(localName = "checkMoveResponse", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.CheckMoveResponse")
    @Action(input = "http://server.lab.recefi.org/Server/checkMoveRequest", output = "http://server.lab.recefi.org/Server/checkMoveResponse")
    public int checkMove();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "makeMove1", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.MakeMove1")
    @ResponseWrapper(localName = "makeMove1Response", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.MakeMove1Response")
    @Action(input = "http://server.lab.recefi.org/Server/makeMove1Request", output = "http://server.lab.recefi.org/Server/makeMove1Response")
    public void makeMove1(
        @WebParam(name = "arg0", targetNamespace = "")
        Cell arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "makeMove2", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.MakeMove2")
    @ResponseWrapper(localName = "makeMove2Response", targetNamespace = "http://server.lab.recefi.org/", className = "org.recefi.lab.webservice.MakeMove2Response")
    @Action(input = "http://server.lab.recefi.org/Server/makeMove2Request", output = "http://server.lab.recefi.org/Server/makeMove2Response")
    public void makeMove2(
        @WebParam(name = "arg0", targetNamespace = "")
        Cell arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Cell arg1);

}
